#!/bin/sh

cat <<!
<!DOCTYPE html>
<html>
	<head>
		<title>Copilot: $TITLE</title>
		<meta charset="utf-8">
		<link rel="stylesheet" href="style.css">
		<link rel="stylesheet" href="haskell.css">
		<link rel="stylesheet" href="home.css">
	<body>
		<div id="page">
			<div id="header">
				<a href="index.html">Copilot</a>
				<span>Realtime Programming Language and Runtime Verification Framework</span>
			</div>
			<div id="menu">$NAV</div>
			<div id="panel">
				<div class="left">
					<p>
						Copilot is a runtime verification framework written in Haskell. It
						allows the user to write programs in a simple but powerful way using
						a stream-based approach.
					</p>
					<p>
						Programs can be interpreted for testing, or translated C99 code to be
						incorporated in a project, or as a standalone application. The C99
						backend ensures us that the output is constant in memory and time,
						making it suitable for systems with hard realtime requirements.
					</p>
				</div>
				<div class="right">
					<pre><code>temp :: Stream Word8
temp = extern "temperature" Nothing

ctemp :: Stream Float
ctemp = (unsafeCast temp) * (150.0 / 255.0) - 50.0

spec = do
  trigger "heaton"  (ctemp < 18.0) [arg ctemp]
  trigger "heatoff" (ctemp > 21.0) [arg ctemp]</code></pre>
				</div>
			</div>
			<div id="content">
				$CONTENT
			</div>
		</div>
	</body>
</html>
!
