name: Publish web
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Install pandoc
        run: |
          sudo apt-get install --yes pandoc

      - name: Build with Pandoc
        run: |
          make

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    needs: build

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
